version: '3.8'

networks:
  shamba:
    external: true

services:
  app:
    image: shamba_lab/v21
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3303/shamba_lab?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: byte
      SPRING_DATASOURCE_PASSWORD: 7fpLxthn
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_JACKSON_SERIALIZATION_FAIL-ON-EMPTY-BEANS: FALSE
      SERVER_PORT: 8081
    volumes:
      - .m2:/root/.m2
    networks:
      shamba:



