server:
  port: 8087

#keycloak:
#  realm: master
#  auth-server-url: http://truby.me.com/auth
#  resource: bb6-js
#  public-client: true
#  bearer-only: true

#logging:git

spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
      api-key: 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 #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
  jta:
    enabled: false
  kafka:
    bootstrap-servers: localhost:29092
  application:
    name:lab
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3303/shamba_lab
    username: root
    password: 2fpLxthn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  #    show-sql: true
  logging:
    level:
      root: debug
      web: debug


app:
  jwtSecret: 'WamlambezWamnyonyez'
  jwtExpirationInMs: 60000000