server:
  port: 8087

#keycloak:
#  realm: master
#  auth-server-url: http://truby.me.com/auth
#  resource: bb6-js
#  public-client: true
#  bearer-only: true

#logging:git

spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
      api-key: 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
  jta:
    enabled: false
  kafka:
    bootstrap-servers: localhost:29092
  application:
    name:lab
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3303/shamba_lab
    username: root
    password: 2fpLxthn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  #    show-sql: true
  logging:
    level:
      root: debug
      web: debug


app:
  jwtSecret: 'WamlambezWamnyonyez'
  jwtExpirationInMs: 60000000